name: Update Gold Price History

on:
  # schedule:
  #   - cron: "5 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up API Key
        run: echo "RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}" >> $GITHUB_ENV

      - name: Fetch Gold Price History
        run: |
          curl --silent \
            --request GET \
            --url "https://gold-prices-pakistan.p.rapidapi.com/history" \
            --header "x-rapidapi-host: gold-prices-pakistan.p.rapidapi.com" \
            --header "x-rapidapi-key: ${RAPIDAPI_KEY}" \
            -o live-prices-history.json

      - name: Commit & Push History
        run: |
          git config user.name "goldpk-bot"
          git config user.email "thesaadarshad+goldpk@gmail.com"
          git add live-prices-history.json
          git commit -m "Auto Update: Gold Price History" || echo "No changes to commit"
          git push
